FROM apache/airflow:3.0.0-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

# CPU-only torch first to prevent CUDA packages being pulled
RUN pip install --no-cache-dir torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir \
    feedparser==6.0.11 \
    requests==2.32.3 \
    beautifulsoup4==4.12.3 \
    lxml==5.3.0 \
    snowflake-connector-python==3.12.3 \
    transformers==4.44.2 \
    vaderSentiment==3.3.2 \
    textblob==0.18.0 \
    mlflow==2.16.2 \
    groq==0.11.0 \
    dbt-snowflake==1.8.4 \
    pandas==2.1.4 \
    python-dotenv==1.0.1
